# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='timer',
            new_name='timer_table',
        ),
    ]
