# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20160803_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer_table',
            name='time',
            field=models.SmallIntegerField(default=0),
        ),
    ]
