# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.SmallIntegerField(default=-10),
        ),
    ]
