# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_question_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='questions',
        ),
        migrations.DeleteModel(
            name='timer_table',
        ),
    ]
