# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20160808_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_response',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_id', models.PositiveSmallIntegerField()),
                ('user_id', models.PositiveSmallIntegerField()),
                ('quiz_id', models.PositiveSmallIntegerField()),
                ('response', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
