# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_user_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='quiz_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
