# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0)),
                ('tag', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
