# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
