# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_questions_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='points',
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
