# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-25 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20160825_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='points',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
