# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('event_name', models.CharField(blank=True, max_length=120, null=True)),
                ('rules', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.CharField(blank=True, max_length=120, null=True)),
                ('venue', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
