# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_data',
            name='description',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
