# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='spons_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image1', models.CharField(blank=True, max_length=120, null=True)),
                ('image2', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
