# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spons_data',
            name='image2',
        ),
    ]
