# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs_data',
            name='blog_image',
        ),
    ]
