# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogs_data_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_data',
            name='body',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
