# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendOtp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_data',
            name='verify',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
