# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendOtp', '0004_gcm_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='gcm',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
