# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendOtp', '0005_user_data_gcm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcm_data',
            name='gcm',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='gcm',
        ),
        migrations.AddField(
            model_name='gcm_data',
            name='fcm',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='fcm',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
