# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20160821_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus_data',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
