# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_auto_20160821_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus_data',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
