# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts_data',
            new_name='contactus_data',
        ),
    ]
