# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20160820_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus_data',
            old_name='number',
            new_name='phone',
        ),
    ]
