# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160824_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_data',
            name='data_type',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home_data',
            name='id',
            field=models.SmallIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
