# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otp_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('otp', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
