# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendOtp', '0003_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='gcm_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcm', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
