# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SendOtp', '0006_auto_20160801_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='gcm_data',
            new_name='fcm_data',
        ),
    ]
