# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendOtp', '0008_auto_20160806_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='user_token_data',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key='True', serialize=False),
        ),
    ]
