# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SendOtp', '0009_auto_20160806_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='fcm__not_registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
