# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='splash_screen_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.PositiveSmallIntegerField()),
                ('compulsary_update', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
