# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Splash_Screen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='splash_screen_model',
            new_name='version_control',
        ),
    ]
